name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.STATIC_BLOG_WEBSITE }}
        TARGET_REPO: a-dream-butterfly/homepage
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn docs:dev && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://home.os0day.cn
